# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/advait/Documents/Coding/HeatSimulation

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/advait/Documents/Coding/HeatSimulation

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/advait/Documents/Coding/HeatSimulation/CMakeFiles /home/advait/Documents/Coding/HeatSimulation/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/advait/Documents/Coding/HeatSimulation/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named HeatSimulation

# Build rule for target.
HeatSimulation: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HeatSimulation
.PHONY : HeatSimulation

# fast build rule for target.
HeatSimulation/fast:
	$(MAKE) -f CMakeFiles/HeatSimulation.dir/build.make CMakeFiles/HeatSimulation.dir/build
.PHONY : HeatSimulation/fast

#=============================================================================
# Target rules for targets named G__HeatSim

# Build rule for target.
G__HeatSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 G__HeatSim
.PHONY : G__HeatSim

# fast build rule for target.
G__HeatSim/fast:
	$(MAKE) -f CMakeFiles/G__HeatSim.dir/build.make CMakeFiles/G__HeatSim.dir/build
.PHONY : G__HeatSim/fast

#=============================================================================
# Target rules for targets named HeatSim

# Build rule for target.
HeatSim: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 HeatSim
.PHONY : HeatSim

# fast build rule for target.
HeatSim/fast:
	$(MAKE) -f CMakeFiles/HeatSim.dir/build.make CMakeFiles/HeatSim.dir/build
.PHONY : HeatSim/fast

G__HeatSim.o: G__HeatSim.cxx.o

.PHONY : G__HeatSim.o

# target to build an object file
G__HeatSim.cxx.o:
	$(MAKE) -f CMakeFiles/HeatSimulation.dir/build.make CMakeFiles/HeatSimulation.dir/G__HeatSim.cxx.o
	$(MAKE) -f CMakeFiles/G__HeatSim.dir/build.make CMakeFiles/G__HeatSim.dir/G__HeatSim.cxx.o
.PHONY : G__HeatSim.cxx.o

G__HeatSim.i: G__HeatSim.cxx.i

.PHONY : G__HeatSim.i

# target to preprocess a source file
G__HeatSim.cxx.i:
	$(MAKE) -f CMakeFiles/HeatSimulation.dir/build.make CMakeFiles/HeatSimulation.dir/G__HeatSim.cxx.i
	$(MAKE) -f CMakeFiles/G__HeatSim.dir/build.make CMakeFiles/G__HeatSim.dir/G__HeatSim.cxx.i
.PHONY : G__HeatSim.cxx.i

G__HeatSim.s: G__HeatSim.cxx.s

.PHONY : G__HeatSim.s

# target to generate assembly for a file
G__HeatSim.cxx.s:
	$(MAKE) -f CMakeFiles/HeatSimulation.dir/build.make CMakeFiles/HeatSimulation.dir/G__HeatSim.cxx.s
	$(MAKE) -f CMakeFiles/G__HeatSim.dir/build.make CMakeFiles/G__HeatSim.dir/G__HeatSim.cxx.s
.PHONY : G__HeatSim.cxx.s

HeatSim.o: HeatSim.cxx.o

.PHONY : HeatSim.o

# target to build an object file
HeatSim.cxx.o:
	$(MAKE) -f CMakeFiles/HeatSimulation.dir/build.make CMakeFiles/HeatSimulation.dir/HeatSim.cxx.o
.PHONY : HeatSim.cxx.o

HeatSim.i: HeatSim.cxx.i

.PHONY : HeatSim.i

# target to preprocess a source file
HeatSim.cxx.i:
	$(MAKE) -f CMakeFiles/HeatSimulation.dir/build.make CMakeFiles/HeatSimulation.dir/HeatSim.cxx.i
.PHONY : HeatSim.cxx.i

HeatSim.s: HeatSim.cxx.s

.PHONY : HeatSim.s

# target to generate assembly for a file
HeatSim.cxx.s:
	$(MAKE) -f CMakeFiles/HeatSimulation.dir/build.make CMakeFiles/HeatSimulation.dir/HeatSim.cxx.s
.PHONY : HeatSim.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... HeatSimulation"
	@echo "... G__HeatSim"
	@echo "... HeatSim"
	@echo "... G__HeatSim.o"
	@echo "... G__HeatSim.i"
	@echo "... G__HeatSim.s"
	@echo "... HeatSim.o"
	@echo "... HeatSim.i"
	@echo "... HeatSim.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

